apiVersion: metrics.keptn.sh/v1
kind: AnalysisDefinition
metadata:
  name: energy-usage
spec:
  objectives:
    - analysisValueTemplateRef:
        name: energy-usage
        namespace: fluentbit
      target:
        failure:
          greaterThan :
            fixedValue: 400000
        warning:
          inRange:
            lowBound: 350000
            highBound: 400000
      weight: 1
      keyObjective: false
  totalScore:
    passPercentage: 90
    warningPercentage: 75