apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      tracing:
        sampling: 100
    defaultProviders:
      tracing:
        - "otelp"
      accessLogging:
        - "envoylogs"
    enablePrometheusMerge: true
    enableTracing: true
    extensionProviders:
      - envoyOtelAls:
          port: 4317
          service: "fluent-bit.fluentbit.svc.cluster.local"
        name: "envoylogs"
      - name: "otelp"
        opentelemetry:
          service: "fluent-bit.fluentbit.svc.cluster.local"
          port: 4317
